td3_kwargs:
  policy_kwargs:
    net_arch: [400, 300]
  learning_rate: 3e-4
  batch_size: 256
  buffer_size: 1000000
  learning_starts: 10000
  train_freq: [1, "step"]
  gradient_steps: 1
  gamma: 0.99
  tau: 0.005
  target_policy_noise: 0.2
  target_noise_clip: 0.5
  verbose: 1
